name: Laravel
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install   
      
      - name: PHPStan
        uses: ./vendor/bin/phpstan 
        with:
            args: analyse

  laravel-tests:
    name: PhpUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit

      - name: Dynamic Badges
        uses: Schneegans/dynamic-badges-action@v1.0.0

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 60fb64f5a477ebb0ebaff3e144df3917
          filename: test.json
          label: Hello
          message: World
          color: orange
